### PR TITLE
Squashed commit of the following:

### PR DESCRIPTION
**Pull request by viv-4**
staff api and postgres
    openshift v4
    single namespace
    seperate release names for third party charts
    internal registry option
    placeos image version update
    gcp https layer 7 lb

This is the merge for feat/staff-api, just forked for ease of squashed commit in the pull request
Multiple features got wrapped up into this branch
Have personally confirmed all works on GKE and Openshift v4
  - GKE now deploys with a layer 7 load balancer which requires the name of a cloud armor security policy, creating this policy in k8s-terraform is on the todo but it is a simple manual process in the meantime

### CODE REVIEW

**Comment by w-le** [comment]
Thanks for all the hard work @viv-4 ,
It looks mostly good to me but correct me if I'm wrong - it looks like the network policies now allow any pod to talk to placeos pods?

I'm not fully qualified to evaluate these changes so I've added @jahoward as a reviewer, thanks!

**Comment by jahoward** [comment]
@w-le That is correct All pods can talk to the placeos pods based on the calico configuration

**Comment by w-le** [comment]
thanks @jahoward ,
so @viv-4 I recommend we ensure that the updated network policies are not significantly looser than they were previously, before pulling this into master.

hey @jahoward can we use some of your billable time for a code review of all these changes in terms of best practices, security and style, with suggested code changes?

**Comment by w-le** [comment]
How's it going? Can I see the changes since our last chat a couple weeks ago?

**Comment by w-le** [comment]
We need to close this one soon @viv-4  it's been very long

**Pull request merged**
